### ISSUE TITLE
[Flutter project] APK file increased by 40% with FreeRASP package

### ISSUE THREAD

**Issue by speszke** [talsec/Free-RASP-Flutter#100]
Hi, 
I've integrated FreeRASP package into the flutter's project and size of APK file (release build) increased from 70MB to 100MB. 
Is this the "price" I have to pay to use the package, or is there a way to not increase the build file's size significantly?

**Comment by tompsota** [comment]
Hi @speszke,

Did you increase the minSdkVersion when you installed freeRASP, or had you this dependency already satisfied? We noticed that bump from minSdkVersion API <23 to API >=23 can lead to notable increases in APK size. However, this increase is not directly caused by freeRASP: since API 23, the native libraries that come with your project are stored uncompressed in the APK (in comparison, in earlier versions, they were compressed). Although your APK might be larger, your application should load faster because the libraries are directly loaded from the APK at runtime. You can read more about it [here](https://stackoverflow.com/questions/68186329/changing-minsdkversion-from-16-to-26-increased-release-apk-size-from-17-to-39-mb).

In our experience, integrating freeRASP typically results in a more modest increase of around 10 MB in the APK size, as in the example app in the freeRASP project.

In your case, one potential solution to consider is to use Android App Bundle, which should result in reducing of the final app size during distribution.

Best,
Tomas, Talsec developer

**Comment by speszke** [comment]
Hi @tompsota ,
Thanks for quick reply. In my case the only change increasing apk size was adding FreeRASP package - nothing else changed. I have `minSdkVersion 23` already set up, so it couldn't impact the size.

**Comment by MajdSallora** [comment]
try add this in manifest in application tag
android:extractNativeLibs="true"

If set to "false", your native libraries are stored uncompressed in the APK. Although your APK might be larger, your application loads faster because the libraries load directly from the APK at runtime.

**Comment by Madanraj1** [comment]
@MajdSallora  thanks this worked

**Comment by yardexx** [comment]
Hello.

I've updated Troubleshooting section in README.md. This change will be reflected in README.md at pub.dev on next update.

Issue will be closed on next freerasp release.
