### ISSUE TITLE
Error on android

### ISSUE THREAD

**Issue by neroaCu** [talsec/Free-RASP-Flutter#11]
Hi, 

I follow the example and got the following error in android.

MissingPluginException(No implementation found for method setConfig on channel plugins.aheaditec.com/config)
I/flutter ( 8987): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)

Could you please help take a look? thanks

**Comment by talsec-app** [comment]
Hello suleymancalikprb
Thank you for your report. 
We are aware of the issue and we are actively looking for solution.
Talsec Team

**Comment by talsec-app** [comment]
Hello.

Are you able to compile application on native side using Android Studio (open android folder as android project in Android Studio).

If not, can you send (paste here) stacktrace (whole exeption)?

Thanks in advance.
Talsec Team

**Comment by talsec-app** [comment]
Thanks for the log.
We are trying our best to resolve the issue.

**Comment by talsec-app** [comment]
We were not able to replicate your problem but after careful inspection of logs and code, we found probable cause of issue.

We would like to ask you if you could try this procedure in order to fix issue:
Find freerasp library in your project (see [this comment](https://github.com/talsec/Free-RASP-Flutter/issues/9#issuecomment-1048843564)) **but** you will go to `src.main/kotlin.com.aheaditec.freerasp/StreamHandlerImpl.kt` and you will add `?` notation to argument `arguments` of `onCancel` function. Same for `events` argument of `onListen` function.
Like so:
```kotlin
    // In StreamHandlerImpl.kt
    
    override fun onListen(arguments: Any?, events: EventChannel.EventSink?) {
            // ... some other code ...
    }

    override fun onCancel(arguments: Any?) {
        talsecApp?.events = null
    }
```
Explanation: According to logs `onCancel` can get null from Java but Kotlin doesnt currently reflect that.
Please let us know, if this solved your issue

**Comment by neroaCu** [comment]
the fix provided by @talsec-app works for me. thanks
