### ISSUE TITLE
Failed build iOS with Codemagic

### ISSUE THREAD

**Issue by santomalau03** [talsec/Free-RASP-Flutter#22]
Hello @talsec-app 
I tried to build and distribute app within codemagic, but i got this error

```
Swift Compiler Error (Xcode): No such module 'TalsecRuntime'
/Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/freerasp-3.0.1/ios/Classes/SwiftFreeraspPlugin.swift:2:7
```

**Comment by talsec-app** [comment]
Hello @santomalau03 , please try the following:

1. Check if the **ios/.symlinks/plugins/freerasp/ios** contains TalsecRuntime.xcframework symbolic link. If not, create it manually in that folder using the following command:
`ln -s ./Debug/TalsecRuntime.xcframework/ TalsecRuntime.xcframework`
If there is no .symlinks folder, create the symlink in the **freerasp-3.0.1/ios** folder.
2. Run `pod install` in the **application ios** folder.

Kind regards,
Talsec team

**Comment by talsec-app** [comment]
Hello @santomalau03 ,

have you managed to solve the issue, or does it still persist? Thank you.

Kind regards,
Talsec team

**Comment by acdwisu** [comment]
Hello @talsec-app ,

I have similar issue when build ios. In ios directory it has contained the `ios/.symlinks/plugins/freerasp/ios/TalsecRuntime.xcframework` symlink.

Thank you

**Comment by acdwisu** [comment]
after some search, 

in my case, it turn out because i targeted build for arm64 and armv7, while the latest freerasp-ios support arm64 and simulator arm64 & x86_x64, therefore define arm64 as build target could resolve my issue.

thx, cmiiw.

**Comment by talsec-app** [comment]
Thank you @acdwisu , we will investigate this further and add the information into the manual.

**Comment by acdwisu** [comment]
thank you @talsec-app

**Comment by tusharanchliyajain** [comment]
@talsec-app Any update on this, @acdwisu any solution how can I fix this ?

**Comment by msikyna** [comment]
Hello @tusharanchliyajain ,
the definition of arm64 as build target did not help?

**Comment by tusharanchliyajain** [comment]
Hey @msikyna,
Not it's not working with arm64 as build target still failing on codemagic build

**Comment by yardexx** [comment]
Hello everyone!

After deep analysis and bug hunting, I was finally able to replicate and track down the issue. To resolve this issue, you have to adjust Codemagic pipeline. Notice that the instructions below apply to the **workflow editor** (not yaml one).

1. Go to **Applications** page where you can see an overview of all of your apps
2. Click the "⚙️" (Settings) button on the project where you use freeRASP
3. You are now in the workflow editor. You should see different settings such as "Build for platforms", "Run build on" and also build stages (Build triggers, Environment variables, Dependency caching, etc.). Now find **Build** stage.
4. Between **Build** and **Tests** stages there is a big "➕"(Add) button (if you haven't changed the pipeline till now). Click on it.
5. Now you'll see two windows: Post-test script and **Pre-build script**. We are going to focus on **Pre-build** one. Copy this script into the **Pre-build script** window.
 
  ```shell
  #!/bin/sh
  flutter pub get
  cd ios
  pod install
  cd .symlinks/plugins/freerasp/iOS
  ln -s Debug/TalsecRuntime.xcframework
  cd ../../../../
  pod install
  ```
  
6. If you already have some content there, just append the script. Please bear in mind your current working directory. 
7. Don't forget to save changes using the save icon in the right top corner.
8. And that's all. Now, if you run the pipeline, it should pass without any problem.
  
Please let us know, if this solution worked for you.

Jaroslav from Talsec Team.

**Comment by tusharanchliyajain** [comment]
@yardexx i used the same script in our code magic flow. I forgot to mention here .. anyways thanks for the reply

**Comment by yardexx** [comment]
@tusharanchliyajain Thank you for your response.

Since solution works for you as well, I am closing this issue. Information about possible issues with Codemagic and how to resolve them will be added into README.md here on GitHub and on next release on pub.dev README as well.

If issue reoccurs, don't hesitate to reopen this issue.

Kind regards,
Jaroslav from Talsec Team

**Comment by yardexx** [comment]
Hello @peer-f 

Apologies for the delay. I'll take look into it ASAP.

Reopening issue

Jaroslav from Talsec

**Comment by yardexx** [comment]
Since its inception, freeRASP has had a crucial feature of distinguishing between dev and release versions. This allows for testing checks without including them in the weekly report, ensuring accurate data. Until freeRASP 4.0.0, this was achieved by using two native SDKs, one for dev and one for release, which were switched based on the type of build (debug/profile/release).

While this approach worked well for Android, it caused a lot of headaches for iOS. Additionally, since [Flutter does not directly support Swift Package Manager](https://github.com/flutter/flutter/issues/33850), it made the situation even more complicated. To resolve this issue, a symlink for the specific SDK is created on build time ([using an integration script provided by the integrator](https://github.com/talsec/Free-RASP-Flutter#ios-setup)), but as you can see, this workaround works _sometimes_ and causes many issues.

To simplify things, the native SDKs were modified so that a single SDK could be used, and a flag would determine whether Talsec operates in dev (false) or release (true - default for security reasons) mode. No changes occur during build time, avoiding any issues with imports.

The new API includes an `isProd` flag in `TalsecConfig`, which is not a breaking change since it has a default value (true).

```dart
final config = TalsecConfig(
    androidConfig: ...,
    // Defaults to true
    // true - release (no need to write explicitly)
    // false - dev
    isProd: false,
)
```

The checks have also been adjusted and updated for better detection and fewer false positives.

If you're testing freeRASP 5.0.0-dev.1 (we're glad to hear that!), don't forget to remove the old iOS integration script and use `isProd` instead. If you spot any issues, please report them by opening an issue. The team is currently testing freeRASP on different environments and with various tooling, including Codemagic, to resolve any issues.

**However, it's important to note that freeRASP 5.0.0-dev.1 should not be considered stable**. We plan to update the API to provide clearer integration. We also plan to merge iOS and Android callbacks into a single callback (e.g. onSimulatorDetected and onEmulatorDetected will be merged) for clearer and less cluttered code.

**Comment by msikyna** [comment]
Hello @peer-f ,
could you try it with the new version? The version is `5.0.0`.

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @peer-f ,
try it with version `5.0.2` please.

Kind regards,
Talsec team
