### ISSUE TITLE
Cannot install app from testflight

### ISSUE THREAD

**Issue by ilia-grishakov-m10** [talsec/Free-RASP-Flutter#38]
Used ios instruction, build is going ok, w/o any problems is deployed to testflight

But cannot install from testflight, shows message, that error occurs while installing

`cd "${SRCROOT}/.symlinks/plugins/freerasp/ios"
if [[ "${CONFIGURATION}" =~ "Release" ]]; then
    rm -rf ./TalsecRuntime.xcframework
    ln -s ./Release/TalsecRuntime.xcframework/ TalsecRuntime.xcframework
else
    rm -rf ./TalsecRuntime.xcframework
    ln -s ./Debug/TalsecRuntime.xcframework/ TalsecRuntime.xcframework
fi
`

"The app cannot be installed because its integrity could not be verified"

**Comment by talsec-app** [comment]
Hello @ilia-grishakov-m10 ,

1. What is the build configurations you use? Is it Debug/Release, or some other configurations?
2. When you remove freeRASP, are you able to install the app? It might be due to [Developer ID Notary Service - Outage](https://developer.apple.com/system-status/), please verify this.
3. Could you show us how you integrated the above script in the Xcode?

Kind regards,
Talsec team

**Comment by msikyna** [comment]
Hello @ilia-grishakov-m10 , according to Apple System Status, it should be now OK.
Were you able to resolve your issue?

Kind regards,
Talsec developer
