### ISSUE TITLE
Shorebird and freeRasp inconvenient

### ISSUE THREAD

**Issue by JgomesAT** [talsec/Free-RASP-Flutter#81]
I'm trying the Shorebird https://shorebird.dev/ for Flutter Code Push, and I did my first push, but I have configured freeRasp and detected and violation of AppIntegrity, I have this configured in my code:

hreatCallback(
      onAppIntegrity: () => DialogUtils.showAlertDialog(
        dismissible: false,
        context: ContextManager.getInstance().currentViewModel!.context,
        title: "App integrity vulnerada, l'app no puede continuar por motivos de segurida",
        negativeButtonTitle: "Sortir de l'app",
        negativeButtonListener: () => SystemNavigator.pop(),
      ),
      
      Can I control that if it's a case of Shorebird don't throw this vulnerability?

**Comment by xprikryl2** [comment]
Hello @JgomesAT,

I checked the concept of Shorebird, but I've not found the concept of how the updates are distributed. If the AppIntegrity threat is triggered, it means that at least one of the `bundle ID/package name` or developer `Team ID/signing certificate` is incorrect, depending on the platform. 

Do you know if this issue is relevant for both Android and iOS? Are you getting the AppIntegrity error right after the app release or only after the first update (code push)? I suspect that the issue is a signing certificate mismatch. If that is indeed the case, it should be enough to add this new signing certificate into your `signingCertificateHashes` array in `TalsecConfig`.

It would be helpful if you could provide us with some information about your configuration (watcher mail), so we can check the audit logs and help you to resolve this issue. You can send us the info to the [info@talsec.app](info@talsec.app) (please also state this issue in the mail as well). 

Best regards,
Talsec Team

**Comment by JgomesAT** [comment]
I tried only in Android, and the error happen after the first push, but maybe your are right with signing certificate mismatch, because Im trying in preview mode and maybe the singing has any changes, thanks by the trick.

the watcher mail is gr_ti_aplicacions_devops@andorratelecom.ad

**Comment by xprikryl2** [comment]
I found several audit logs with AppIntegrity on Android for the given mail. All of them are referring to the signing certificate mismatch.
I will send you an email (to this given mail) with detailed information and expected signing certificate values. Adding this new signing certificate to your configuration should resolve your issues.

**Comment by JgomesAT** [comment]
Thanks a lot, now is working fine
