### ISSUE TITLE
Which callback?

### ISSUE THREAD

**Issue by rodrifting** [talsec/Free-RASP-Flutter#96]
I can not say this is a bug but it is not a suggestion either.

I've made a research on OS, YouTube and GitHub. 
I followed the steps described on https://pub.dev/packages/freerasp and everything seems to be working fine. 

The question is, should I use the ThreatCallback or the TalsecCallback? Each callback checks for not the same things exactly.

    void main() async {
           WidgetsFlutterBinding.ensureInitialized();
    ...
        // create configuration for freeRASP
        final config = TalsecConfig(
        /// For Android
        androidConfig: AndroidConfig(
            packageName: 'com.tada.tadaaa',
            signingCertHashes: ['dslkhfsdakjhfkjdshfkdshkfdsh'],
            supportedStores: ['adb', 'com.sec.android.app.samsungapps'],
        ),

        /// For iOS
        iosConfig: IOSConfig(
            bundleIds: ['com.tada.tadAAAA'],
            teamId: 'fsdjhgfksjdhgj',
        ),

        watcherMail: 'john@doe.com',

        isProd: false,
     );

     // Setting up callbacks
     final callback = ThreatCallback(
         onAppIntegrity: () => print("App integrity"),
         onObfuscationIssues: () => print("Obfuscation issues"),
         onDebug: () => print("Debugging"),
         onDeviceBinding: () => print("Device binding"),
         onDeviceID: () => print("Device ID"),
         onHooks: () => print("Hooks"),
         onPasscode: () => print("Passcode not set"),
         onPrivilegedAccess: () => print("Privileged access"),
         onSecureHardwareNotAvailable: () => print("Secure hardware not available"),
         onSimulator: () => print("Simulator"),
         onUnofficialStore: () => print("Unofficial store"));

         // Attaching listener
         Talsec.instance.attachListener(callback);

         await Talsec.instance.start(config);

         ...

         runApp(const App());
    }
    
As a side note an easier way to get your android app hash if you can not run the Gradle Task is: 
Google Play Console > View App > Setup > App Signing > App Signing Key Certificate > SHA 256. 
Then use https://base64.guru/converter/encode/hex as suggested.

Thanks

**Comment by msikyna** [comment]
Hello @rodrifting , 
thank you for the question! I will let @tompsota or @yardexx answer and add the information into the documentation.

**Comment by tompsota** [comment]
Hi @rodrifting,

1. Callbacks

> should I use the ThreatCallback or the TalsecCallback?

TalsecCallback was removed in freeRASP 5.0.0, therefore this depends on the version of freeRASP you are using. For freeRASP < 5.0.0, you should use `TalsecCallback`. For newer versions, the preferred method is to use `ThreatCallback`. 

> Each callback checks for not the same things exactly

They both check for the same threats, we just unified the interface for iOS and Android since v5.0.0. For example, `onRootDetected` from old `AndroidCallback` and `onJailbreakDetected` from old `iOSCallback` were unified into `onPrivilegedAccess` in the `ThreatCallback`. Therefore, you don't receive root and jailbreak callbacks separately, but instead get privilegedAccess regardless of the platform.

2. Getting android app hash
We updated our wiki with the correct way how to obtain the certificate hash from Google Play Console. Thank you for pointing this out.

If you have any other questions feel free to ask.


Cheers,

Tomas, Talsec developer

**Comment by rodrifting** [comment]
Thank you!
